--菜单-用户视图
CREATE VIEW V_MENU_USER AS
SELECT A.*,D.USER_ID FROM T_MENU A
LEFT JOIN T_PERM B ON B.MENU_ID=A.MENU_ID
LEFT JOIN T_ROLE C ON C.ROLE_ID=B.ROLE_ID
LEFT JOIN T_USER D ON D.ROLE_ID=C.ROLE_ID
ORDER BY A.MENU_ID;


--一卡通消费记录视图
CREATE VIEW V_RECORD AS
SELECT A.RECORD_ID,A.CARD_ID,A.AMOUNT,A.RECORD_TIME,B.PARAM_ID,B.PARAM_NAME,B.PARAM_TYPE,B.PARAM_VALUE,B.PARAM_STATE,C.* FROM T_RECORD A
LEFT JOIN T_PARAM B ON B.PARAM_ID=A.PARAM_NAME_ID
LEFT JOIN T_USER C ON C.USER_ID=A.USER_ID;


--一卡通视图
CREATE VIEW V_CARD AS
SELECT A.CARD_ID,A.CARD_CODE,A.CREATE_TIME,
A.SALE_USER_ID,E.NAME SALE_NAME,A.SALE_TIME,
A.APPLY_ID,
C.APPLY_USER_ID,F.NAME APPLY_NAME,C.APPLY_TIME,
C.AUDIT_USER_ID,G.NAME AUDIT_NAME,C.AUDIT_TIME,
A.PATIENT_ID,D.NAME PATIENT_NAME,
A.PARAM_STATE_ID,B.PARAM_NAME,A.AMOUNT
FROM T_CARD A
LEFT JOIN T_PARAM B ON B.PARAM_ID=A.PARAM_STATE_ID 
LEFT JOIN T_APPLY C ON C.APPLY_ID=A.APPLY_ID
LEFT JOIN T_PATIENT D ON D.PATIENT_ID=A.PATIENT_ID
LEFT JOIN T_USER E ON E.USER_ID=A.SALE_USER_ID
LEFT JOIN T_USER F ON F.USER_ID=C.APPLY_USER_ID
LEFT JOIN T_USER G ON G.USER_ID=C.AUDIT_USER_ID
LEFT JOIN T_PARAM H ON H.PARAM_ID=C.PARAM_STATE_ID
ORDER BY CARD_ID;



--工作量统计视图
CREATE VIEW V_STATISTICS AS
SELECT A.USER_ID,A.NAME,
COUNT(CASE WHEN B.LOG_NAME='出售一卡通' THEN B.LOG_NAME END) AS SOLD,
COUNT(CASE WHEN B.LOG_NAME='更换一卡通' THEN B.LOG_NAME END)AS CHANGE,
COUNT(CASE WHEN B.LOG_NAME='退卡' THEN B.LOG_NAME END) AS REFUND,
COUNT(CASE WHEN B.LOG_NAME='登记处方' THEN B.LOG_NAME END) AS PRES_REG,
COUNT(CASE WHEN B.LOG_NAME='处方退费' THEN B.LOG_NAME END) AS REFUND_PRES
FROM T_USER A
LEFT JOIN T_LOG B ON B.USER_ID=A.USER_ID
LEFT JOIN T_ROLE C ON C.ROLE_ID=A.ROLE_ID
WHERE A.ROLE_ID!=3
GROUP BY A.USER_ID,A.NAME
ORDER BY NLSSORT(A.NAME,'NLS_SORT=SCHINESE_PINYIN_M');


--菜单-角色视图
CREATE VIEW V_MENU_ROLE AS
SELECT A.*,C.ROLE_ID,D.MENU_NAME AS PARENT_NAME FROM T_MENU A
LEFT JOIN T_PERM B ON B.MENU_ID=A.MENU_ID
LEFT  JOIN T_ROLE C ON C.ROLE_ID=B.ROLE_ID
LEFT  JOIN T_MENU D ON D.MENU_ID=A.PARENT_ID
WHERE A.PARENT_ID!=0
ORDER BY A.MENU_ID;

--日志-用户视图
CREATE VIEW V_LOG_USER AS
SELECT A.*,B.NAME FROM T_LOG A
INNER JOIN T_USER B ON A.USER_ID=B.USER_ID;


--用户视图
CREATE VIEW V_USER AS
SELECT A.USER_ID,A.NAME,A.ROLE_ID,B.ROLE_NAME,A.PARAM_SECTION_ID,C.PARAM_NAME AS SECTION,A.PARAM_STATE_ID,D.PARAM_NAME AS STATE FROM T_USER A
INNER JOIN T_ROLE B ON B.ROLE_ID=A.ROLE_ID
INNER JOIN T_PARAM C ON C.PARAM_ID=A.PARAM_SECTION_ID
INNER JOIN T_PARAM D ON D.PARAM_ID=A.PARAM_STATE_ID;

--一卡通申请视图
CREATE VIEW V_APPLY AS
SELECT A.APPLY_ID,A.APPLY_TIME,A.APPLY_NUM,A.APPLY_USER_ID,B.NAME AS APPLY_USER,
A.AUDIT_USER_ID,C.NAME AS AUDIT_USER,
A.PARAM_STATE_ID,D.PARAM_NAME AS STATE,A.AUDIT_TIME 
FROM T_APPLY A
LEFT JOIN T_USER B ON B.USER_ID=A.APPLY_USER_ID
LEFT JOIN T_USER C ON C.USER_ID=A.AUDIT_USER_ID
LEFT JOIN T_PARAM D ON D.PARAM_ID=A.PARAM_STATE_ID;





