--创建序列
CREATE SEQUENCE SEQ_PARAM;
CREATE SEQUENCE SEQ_LOG;
CREATE SEQUENCE SEQ_USER;
CREATE SEQUENCE SEQ_ROLE;
CREATE SEQUENCE SEQ_PERM;
CREATE SEQUENCE SEQ_MENU;
CREATE SEQUENCE SEQ_CARD;
CREATE SEQUENCE SEQ_APPLY;
CREATE SEQUENCE SEQ_RECORD;
CREATE SEQUENCE SEQ_PATIENT;
CREATE SEQUENCE SEQ_PRES;
CREATE SEQUENCE SEQ_APPOINT;
--参数表(数据字典表)
CREATE TABLE T_PARAM (
	PARAM_ID NUMBER,
	PARAM_NAME VARCHAR2 ( 20 ),
	PARAM_TYPE VARCHAR2 ( 30 ),
	PARAM_VALUE NUMBER,
	PARAM_STATE VARCHAR2 ( 20 ),
	DESC_INFO VARCHAR2 ( 100 ),
	CONSTRAINT PK_PARAM PRIMARY KEY ( PARAM_ID ) 
) SEGMENT CREATION IMMEDIATE;
COMMENT ON TABLE T_PARAM IS '参数表(数据字典表)';
COMMENT ON COLUMN T_PARAM.PARAM_ID IS '参数ID';
COMMENT ON COLUMN T_PARAM.PARAM_NAME IS '参数名称';
COMMENT ON COLUMN T_PARAM.PARAM_TYPE IS '参数类型';
COMMENT ON COLUMN T_PARAM.PARAM_VALUE IS '参数值';
COMMENT ON COLUMN T_PARAM.PARAM_STATE IS '参数状态(可用或不可用)';
COMMENT ON COLUMN T_PARAM.DESC_INFO IS '描述';
--日志表
CREATE TABLE T_LOG (
	LOG_ID NUMBER,
	USER_ID NUMBER,
	LOG_NAME VARCHAR2 ( 30 ),
	LOG_TIME DATE,
	DESC_INFO VARCHAR2 ( 100 ),
	CONSTRAINT PK_LOG PRIMARY KEY ( LOG_ID ) 
) SEGMENT CREATION IMMEDIATE;
COMMENT ON TABLE T_LOG IS '日志表';
COMMENT ON COLUMN T_LOG.LOG_ID IS '日志ID';
COMMENT ON COLUMN T_LOG.USER_ID IS '用户ID';
COMMENT ON COLUMN T_LOG.LOG_NAME IS '操作名称';
COMMENT ON COLUMN T_LOG.LOG_TIME IS '日志时间';
COMMENT ON COLUMN T_LOG.DESC_INFO IS '描述';
--后台用户表
CREATE TABLE T_USER (
	USER_ID NUMBER,
	USERNAME VARCHAR2 ( 20 ),
	PASSWORD VARCHAR2 ( 20 ),
	NAME VARCHAR2 ( 20 ),
	ROLE_ID NUMBER,
	PARAM_SECTION_ID NUMBER,
	PARAM_STATE_ID NUMBER,
	DESC_INFO VARCHAR2 ( 200 ),
	CONSTRAINT PK_USER PRIMARY KEY ( USER_ID ) 
) SEGMENT CREATION IMMEDIATE;
COMMENT ON TABLE T_USER IS '后台用户表';
COMMENT ON COLUMN T_USER.USER_ID IS '用户ID';
COMMENT ON COLUMN T_USER.USERNAME IS '用户名';
COMMENT ON COLUMN T_USER.PASSWORD IS '密码';
COMMENT ON COLUMN T_USER.NAME IS '姓名';
COMMENT ON COLUMN T_USER.ROLE_ID IS '角色ID';
COMMENT ON COLUMN T_USER.PARAM_SECTION_ID IS '参数：科室ID';
COMMENT ON COLUMN T_USER.PARAM_STATE_ID IS '参数：后台用户状态ID';
COMMENT ON COLUMN T_USER.DESC_INFO IS '描述';
--角色表
CREATE TABLE T_ROLE (
	ROLE_ID NUMBER,
	ROLE_NAME VARCHAR2 ( 20 ),
	DESC_INFO VARCHAR2 ( 200 ),
	CONSTRAINT PK_ROLE PRIMARY KEY ( ROLE_ID ) 
) SEGMENT CREATION IMMEDIATE;
COMMENT ON TABLE T_ROLE IS '角色表';
COMMENT ON COLUMN T_ROLE.ROLE_ID IS '角色ID';
COMMENT ON COLUMN T_ROLE.ROLE_NAME IS '角色名';
COMMENT ON COLUMN T_ROLE.DESC_INFO IS '描述';
--权限表
CREATE TABLE T_PERM (
	PERM_ID NUMBER,
	ROLE_ID NUMBER,
	MENU_ID NUMBER,
	DESC_INFO VARCHAR2 ( 200 ),
	CONSTRAINT PK_MENU_ROLE PRIMARY KEY ( PERM_ID ) 
) SEGMENT CREATION IMMEDIATE;
COMMENT ON TABLE T_PERM IS '权限表';
COMMENT ON COLUMN T_PERM.PERM_ID IS '权限ID';
COMMENT ON COLUMN T_PERM.ROLE_ID IS '角色ID';
COMMENT ON COLUMN T_PERM.MENU_ID IS '菜单ID';
COMMENT ON COLUMN T_PERM.DESC_INFO IS '描述';
--菜单表
CREATE TABLE T_MENU (
	MENU_ID NUMBER,
	MENU_SEQ NUMBER,
	MENU_NAME VARCHAR2 ( 20 ),
	PAGE_HREF VARCHAR2 ( 200 ),
	DESC_INFO VARCHAR2 ( 200 ),
	PARENT_ID NUMBER,
	CONSTRAINT PK_MENU PRIMARY KEY ( MENU_ID ) 
) SEGMENT CREATION IMMEDIATE;
COMMENT ON TABLE T_MENU IS '菜单表';
COMMENT ON COLUMN T_MENU.MENU_ID IS '菜单ID';
COMMENT ON COLUMN T_MENU.MENU_SEQ IS '菜单排序号';
COMMENT ON COLUMN T_MENU.MENU_NAME IS '菜单名称';
COMMENT ON COLUMN T_MENU.PAGE_HREF IS '菜单页面地址';
COMMENT ON COLUMN T_MENU.DESC_INFO IS '描述';
COMMENT ON COLUMN T_MENU.PARENT_ID IS '菜单父ID(0表示一级菜单)';
--一卡通表
CREATE TABLE T_CARD (
	CARD_ID NUMBER,
	CARD_CODE VARCHAR2(13),
	CREATE_TIME DATE,
	SALE_TIME DATE,
	APPLY_ID NUMBER,
	SALE_USER_ID NUMBER,
	PATIENT_ID NUMBER,
	PARAM_STATE_ID NUMBER,
	AMOUNT NUMBER,
	DEPOSIT NUMBER,
	DESC_INFO VARCHAR2 ( 200 ),
	CONSTRAINT PK_CARD PRIMARY KEY ( CARD_ID ) 
) SEGMENT CREATION IMMEDIATE;
COMMENT ON TABLE T_CARD IS '一卡通表';
COMMENT ON COLUMN T_CARD.CARD_ID IS '一卡通ID';
COMMENT ON COLUMN T_CARD.CARD_CODE IS '一卡通卡号';
COMMENT ON COLUMN T_CARD.CREATE_TIME IS '入库时间';
COMMENT ON COLUMN T_CARD.SALE_TIME IS '出售时间';
COMMENT ON COLUMN T_CARD.APPLY_ID IS '申请ID';
COMMENT ON COLUMN T_CARD.SALE_USER_ID IS '售卡人ID';
COMMENT ON COLUMN T_CARD.PATIENT_ID IS '就诊人ID';
COMMENT ON COLUMN T_CARD.PARAM_STATE_ID IS '参数：一卡通状态ID';
COMMENT ON COLUMN T_CARD.AMOUNT IS '一卡通余额';
COMMENT ON COLUMN T_CARD.DEPOSIT IS '一卡通押金';
COMMENT ON COLUMN T_CARD.DESC_INFO IS '描述';
--一卡通申请表
CREATE TABLE T_APPLY (
	APPLY_ID NUMBER,
	APPLY_TIME DATE,
	APPLY_NUM NUMBER,
	APPLY_USER_ID NUMBER,
	AUDIT_USER_ID NUMBER,
	PARAM_STATE_ID NUMBER,
	AUDIT_TIME DATE,
	DESC_INFO VARCHAR2 ( 200 ),
	CONSTRAINT PK_APPLY PRIMARY KEY ( APPLY_ID ) 
) SEGMENT CREATION IMMEDIATE;
COMMENT ON TABLE T_APPLY IS '一卡通申请表';
COMMENT ON COLUMN T_APPLY.APPLY_ID IS '申请ID';
COMMENT ON COLUMN T_APPLY.APPLY_TIME IS '申请时间';
COMMENT ON COLUMN T_APPLY.APPLY_NUM IS '申请数量';
COMMENT ON COLUMN T_APPLY.APPLY_USER_ID IS '申请人ID';
COMMENT ON COLUMN T_APPLY.AUDIT_USER_ID IS '审核人ID';
COMMENT ON COLUMN T_APPLY.PARAM_STATE_ID IS '参数：一卡通申请状态ID';
COMMENT ON COLUMN T_APPLY.AUDIT_TIME IS '审核时间';
COMMENT ON COLUMN T_APPLY.DESC_INFO IS '描述';
--消费记录表
CREATE TABLE T_RECORD (
	RECORD_ID NUMBER,
	CARD_ID NUMBER,
	PARAM_NAME_ID NUMBER,
	AMOUNT NUMBER,
	USER_ID NUMBER,
	RECORD_TIME DATE,
	DESC_INFO VARCHAR2 ( 200 ),
	CONSTRAINT PK_RECORD PRIMARY KEY ( RECORD_ID ) 
) SEGMENT CREATION IMMEDIATE;
COMMENT ON TABLE T_RECORD IS '消费记录表';
COMMENT ON COLUMN T_RECORD.RECORD_ID IS '消费记录ID';
COMMENT ON COLUMN T_RECORD.CARD_ID IS '一卡通ID';
COMMENT ON COLUMN T_RECORD.PARAM_NAME_ID IS '参数：消费记录名称ID';
COMMENT ON COLUMN T_RECORD.AMOUNT IS '发生金额';
COMMENT ON COLUMN T_RECORD.USER_ID IS '后台执行人ID';
COMMENT ON COLUMN T_RECORD.RECORD_TIME IS '记录时间';
COMMENT ON COLUMN T_RECORD.DESC_INFO IS '描述';
--就诊人表
CREATE TABLE T_PATIENT (
	PATIENT_ID NUMBER,
	NAME VARCHAR2 ( 20 ),
	AGE NUMBER,
	WEEK NUMBER,
	SEX CHAR ( 3 ),
	NATIVE_PLACE VARCHAR2 ( 20 ),
	ID_CARD CHAR ( 18 ),
	PHONE CHAR ( 11 ),
	ADDR VARCHAR2 ( 200 ),
	DESC_INFO VARCHAR2 ( 200 ),
	CONSTRAINT PK_PATIENT PRIMARY KEY ( PATIENT_ID ) 
) SEGMENT CREATION IMMEDIATE;
COMMENT ON TABLE T_PATIENT IS '就诊人表';
COMMENT ON COLUMN T_PATIENT.PATIENT_ID IS '就诊人ID';
COMMENT ON COLUMN T_PATIENT.NAME IS '姓名';
COMMENT ON COLUMN T_PATIENT.AGE IS '年龄';
COMMENT ON COLUMN T_PATIENT.WEEK IS '周';
COMMENT ON COLUMN T_PATIENT.SEX IS '性别';
COMMENT ON COLUMN T_PATIENT.NATIVE_PLACE IS '籍贯';
COMMENT ON COLUMN T_PATIENT.ID_CARD IS '身份证号';
COMMENT ON COLUMN T_PATIENT.PHONE IS '联系电话';
COMMENT ON COLUMN T_PATIENT.ADDR IS '地址';
COMMENT ON COLUMN T_PATIENT.DESC_INFO IS '描述';
--处方表
CREATE TABLE T_PRES (
	PRES_ID NUMBER,
	CARD_ID NUMBER,
	NAME VARCHAR2(20),
	TAKE VARCHAR2(20),
	NUM NUMBER,
	UNIT CHAR(9),
	PRICE NUMBER,
	CREATE_TIME DATE,
	PARAM_STATE_ID NUMBER,
	CONSTRAINT PK_PRESCRIPTION PRIMARY KEY ( PRES_ID ) 
) SEGMENT CREATION IMMEDIATE;
COMMENT ON TABLE T_PRES IS '处方表';
COMMENT ON COLUMN T_PRES.PRES_ID IS '处方ID';
COMMENT ON COLUMN T_PRES.CARD_ID IS '一卡通ID';
COMMENT ON COLUMN T_PRES.TAKE IS '处方名称';
COMMENT ON COLUMN T_PRES.TAKE IS '服用方式';
COMMENT ON COLUMN T_PRES.NUM IS '数量';
COMMENT ON COLUMN T_PRES.UNIT IS '处方单位';
COMMENT ON COLUMN T_PRES.PRICE IS '单价';
COMMENT ON COLUMN T_PRES.CREATE_TIME IS '处方时间';
COMMENT ON COLUMN T_PRES.PARAM_STATE_ID IS '参数：处方状态ID';
--预约表
CREATE TABLE T_APPOINT (
	APPOINT_ID NUMBER,
	USER_ID NUMBER,
	WORK_TIME DATE,
	APPOINT_TIME DATE,
	CLINIC_TIME DATE,
	PATIENT_ID NUMBER,
	PARAM_STATE_ID NUMBER,
	CONSTRAINT PK_APPOINT PRIMARY KEY ( APPOINT_ID ) 
) SEGMENT CREATION IMMEDIATE;
COMMENT ON TABLE T_APPOINT IS '预约表';
COMMENT ON COLUMN T_APPOINT.APPOINT_ID IS '预约ID';
COMMENT ON COLUMN T_APPOINT.USER_ID IS '用户(医生)ID';
COMMENT ON COLUMN T_APPOINT.WORK_TIME IS '门诊时间';
COMMENT ON COLUMN T_APPOINT.APPOINT_TIME IS '预约时间';
COMMENT ON COLUMN T_APPOINT.CLINIC_TIME IS '就诊时间';
COMMENT ON COLUMN T_APPOINT.PATIENT_ID IS '就诊人ID';
COMMENT ON COLUMN T_APPOINT.PARAM_STATE_ID IS '参数：预约状态ID';