--删除序列
DROP SEQUENCE SEQ_PARAM;
DROP SEQUENCE SEQ_LOG;
DROP SEQUENCE SEQ_USER;
DROP SEQUENCE SEQ_ROLE;
DROP SEQUENCE SEQ_PERM;
DROP SEQUENCE SEQ_MENU;
DROP SEQUENCE SEQ_CARD;
DROP SEQUENCE SEQ_APPLY;
DROP SEQUENCE SEQ_RECORD;
DROP SEQUENCE SEQ_PATIENT;
DROP SEQUENCE SEQ_PRES;
DROP SEQUENCE SEQ_APPOINT;
--删除表
--参数表(数据字典表)
DROP TABLE T_PARAM;
--日志表
DROP TABLE T_LOG;
--后台用户表
DROP TABLE T_USER;
--角色表
DROP TABLE T_ROLE;
--权限表
DROP TABLE T_PERM;
--菜单表
DROP TABLE T_MENU;
--一卡通表
DROP TABLE T_CARD;
--一卡通申请表
DROP TABLE T_APPLY;
--消费记录表
DROP TABLE T_RECORD;
--就诊人表
DROP TABLE T_PATIENT;
--处方表
DROP TABLE T_PRES;
--预约表
DROP TABLE T_APPOINT;