--参数表
INSERT INTO T_PARAM (PARAM_ID,PARAM_NAME,PARAM_TYPE,PARAM_VALUE,PARAM_STATE,DESC_INFO ) VALUES (SEQ_PARAM.NEXTVAL,'启用','用户状态',1,'可用','');
INSERT INTO T_PARAM (PARAM_ID,PARAM_NAME,PARAM_TYPE,PARAM_VALUE,PARAM_STATE,DESC_INFO ) VALUES (SEQ_PARAM.NEXTVAL,'禁用','用户状态',1,'可用','');
INSERT INTO T_PARAM (PARAM_ID,PARAM_NAME,PARAM_TYPE,PARAM_VALUE,PARAM_STATE,DESC_INFO ) VALUES (SEQ_PARAM.NEXTVAL,'删除','用户状态',2,'可用','');
INSERT INTO T_PARAM (PARAM_ID,PARAM_NAME,PARAM_TYPE,PARAM_VALUE,PARAM_STATE,DESC_INFO ) VALUES (SEQ_PARAM.NEXTVAL,'待领用','一卡通状态',1,'可用','');
INSERT INTO T_PARAM (PARAM_ID,PARAM_NAME,PARAM_TYPE,PARAM_VALUE,PARAM_STATE,DESC_INFO ) VALUES (SEQ_PARAM.NEXTVAL,'已出售','一卡通状态',1,'可用','');
INSERT INTO T_PARAM (PARAM_ID,PARAM_NAME,PARAM_TYPE,PARAM_VALUE,PARAM_STATE,DESC_INFO ) VALUES (SEQ_PARAM.NEXTVAL,'已注销','一卡通状态',1,'可用','');
INSERT INTO T_PARAM (PARAM_ID,PARAM_NAME,PARAM_TYPE,PARAM_VALUE,PARAM_STATE,DESC_INFO ) VALUES (SEQ_PARAM.NEXTVAL,'待出售','一卡通状态',2,'可用','');
INSERT INTO T_PARAM (PARAM_ID,PARAM_NAME,PARAM_TYPE,PARAM_VALUE,PARAM_STATE,DESC_INFO ) VALUES (SEQ_PARAM.NEXTVAL,'已损坏','一卡通状态',2,'可用','');
INSERT INTO T_PARAM (PARAM_ID,PARAM_NAME,PARAM_TYPE,PARAM_VALUE,PARAM_STATE,DESC_INFO ) VALUES (SEQ_PARAM.NEXTVAL,'待审核','一卡通申请状态',1,'可用','');
INSERT INTO T_PARAM (PARAM_ID,PARAM_NAME,PARAM_TYPE,PARAM_VALUE,PARAM_STATE,DESC_INFO ) VALUES (SEQ_PARAM.NEXTVAL,'已审核','一卡通申请状态',2,'可用','');
INSERT INTO T_PARAM (PARAM_ID,PARAM_NAME,PARAM_TYPE,PARAM_VALUE,PARAM_STATE,DESC_INFO ) VALUES (SEQ_PARAM.NEXTVAL,'售卡','消费记录事项',1,'可用','');
INSERT INTO T_PARAM (PARAM_ID,PARAM_NAME,PARAM_TYPE,PARAM_VALUE,PARAM_STATE,DESC_INFO ) VALUES (SEQ_PARAM.NEXTVAL,'充值','消费记录事项',2,'可用','');
INSERT INTO T_PARAM (PARAM_ID,PARAM_NAME,PARAM_TYPE,PARAM_VALUE,PARAM_STATE,DESC_INFO ) VALUES (SEQ_PARAM.NEXTVAL,'挂号','消费记录事项',3,'可用','');
INSERT INTO T_PARAM (PARAM_ID,PARAM_NAME,PARAM_TYPE,PARAM_VALUE,PARAM_STATE,DESC_INFO ) VALUES (SEQ_PARAM.NEXTVAL,'撤销挂号','消费记录事项',4,'可用','');
INSERT INTO T_PARAM (PARAM_ID,PARAM_NAME,PARAM_TYPE,PARAM_VALUE,PARAM_STATE,DESC_INFO ) VALUES (SEQ_PARAM.NEXTVAL,'处方','消费记录事项',5,'可用','');
INSERT INTO T_PARAM (PARAM_ID,PARAM_NAME,PARAM_TYPE,PARAM_VALUE,PARAM_STATE,DESC_INFO ) VALUES (SEQ_PARAM.NEXTVAL,'处方退款','消费记录事项',6,'可用','');
INSERT INTO T_PARAM (PARAM_ID,PARAM_NAME,PARAM_TYPE,PARAM_VALUE,PARAM_STATE,DESC_INFO ) VALUES (SEQ_PARAM.NEXTVAL,'已付款','处方状态',2,'可用','');
INSERT INTO T_PARAM (PARAM_ID,PARAM_NAME,PARAM_TYPE,PARAM_VALUE,PARAM_STATE,DESC_INFO ) VALUES (SEQ_PARAM.NEXTVAL,'退款','处方状态',3,'可用','');
INSERT INTO T_PARAM (PARAM_ID,PARAM_NAME,PARAM_TYPE,PARAM_VALUE,PARAM_STATE,DESC_INFO ) VALUES (SEQ_PARAM.NEXTVAL,'未预约','预约状态',1,'可用','');
INSERT INTO T_PARAM (PARAM_ID,PARAM_NAME,PARAM_TYPE,PARAM_VALUE,PARAM_STATE,DESC_INFO ) VALUES (SEQ_PARAM.NEXTVAL,'已预约','预约状态',2,'可用','');
INSERT INTO T_PARAM (PARAM_ID,PARAM_NAME,PARAM_TYPE,PARAM_VALUE,PARAM_STATE,DESC_INFO ) VALUES (SEQ_PARAM.NEXTVAL,'已过期','预约状态',3,'可用','');
INSERT INTO T_PARAM (PARAM_ID,PARAM_NAME,PARAM_TYPE,PARAM_VALUE,PARAM_STATE,DESC_INFO ) VALUES (SEQ_PARAM.NEXTVAL,'内科','科室',1,'可用','');
INSERT INTO T_PARAM (PARAM_ID,PARAM_NAME,PARAM_TYPE,PARAM_VALUE,PARAM_STATE,DESC_INFO ) VALUES (SEQ_PARAM.NEXTVAL,'外科','科室',2,'可用','');
INSERT INTO T_PARAM (PARAM_ID,PARAM_NAME,PARAM_TYPE,PARAM_VALUE,PARAM_STATE,DESC_INFO ) VALUES (SEQ_PARAM.NEXTVAL,'五官科','科室',3,'可用','');
INSERT INTO T_PARAM (PARAM_ID,PARAM_NAME,PARAM_TYPE,PARAM_VALUE,PARAM_STATE,DESC_INFO ) VALUES (SEQ_PARAM.NEXTVAL,'骨科','科室',4,'可用','');
--角色表
INSERT INTO T_ROLE (ROLE_ID,ROLE_NAME,DESC_INFO) VALUES (SEQ_ROLE.NEXTVAL,'医生','');
INSERT INTO T_ROLE (ROLE_ID,ROLE_NAME,DESC_INFO) VALUES (SEQ_ROLE.NEXTVAL,'收费员','');
INSERT INTO T_ROLE (ROLE_ID,ROLE_NAME,DESC_INFO) VALUES (SEQ_ROLE.NEXTVAL,'管理员','');
--菜单表
INSERT INTO T_MENU (MENU_ID,MENU_SEQ,MENU_NAME,PAGE_HREF,DESC_INFO,PARENT_ID) VALUES (SEQ_MENU.NEXTVAL,1,'诊疗工作','','',0);
INSERT INTO T_MENU (MENU_ID,MENU_SEQ,MENU_NAME,PAGE_HREF,DESC_INFO,PARENT_ID) VALUES (SEQ_MENU.NEXTVAL,2,'卡片业务','','',0);
INSERT INTO T_MENU (MENU_ID,MENU_SEQ,MENU_NAME,PAGE_HREF,DESC_INFO,PARENT_ID) VALUES (SEQ_MENU.NEXTVAL,3,'日常事务','','',0);
INSERT INTO T_MENU (MENU_ID,MENU_SEQ,MENU_NAME,PAGE_HREF,DESC_INFO,PARENT_ID) VALUES (SEQ_MENU.NEXTVAL,4,'统计查询','','',0);
INSERT INTO T_MENU (MENU_ID,MENU_SEQ,MENU_NAME,PAGE_HREF,DESC_INFO,PARENT_ID) VALUES (SEQ_MENU.NEXTVAL,5,'辅助功能','','',0);
INSERT INTO T_MENU (MENU_ID,MENU_SEQ,MENU_NAME,PAGE_HREF,DESC_INFO,PARENT_ID) VALUES (SEQ_MENU.NEXTVAL,6,'卡片管理','','',0);
INSERT INTO T_MENU (MENU_ID,MENU_SEQ,MENU_NAME,PAGE_HREF,DESC_INFO,PARENT_ID) VALUES (SEQ_MENU.NEXTVAL,7,'系统管理','','',0);

INSERT INTO T_MENU (MENU_ID,MENU_SEQ,MENU_NAME,PAGE_HREF,DESC_INFO,PARENT_ID) VALUES (SEQ_MENU.NEXTVAL,8,'处方登记','clinic/pres_reg.jsp','',1);
INSERT INTO T_MENU (MENU_ID,MENU_SEQ,MENU_NAME,PAGE_HREF,DESC_INFO,PARENT_ID) VALUES (SEQ_MENU.NEXTVAL,9,'领卡','card/receive.jsp','',2);
INSERT INTO T_MENU (MENU_ID,MENU_SEQ,MENU_NAME,PAGE_HREF,DESC_INFO,PARENT_ID) VALUES (SEQ_MENU.NEXTVAL,10,'售卡','card/sale.jsp','',2);
INSERT INTO T_MENU (MENU_ID,MENU_SEQ,MENU_NAME,PAGE_HREF,DESC_INFO,PARENT_ID) VALUES (SEQ_MENU.NEXTVAL,11,'换卡','card/change.jsp','',2);
INSERT INTO T_MENU (MENU_ID,MENU_SEQ,MENU_NAME,PAGE_HREF,DESC_INFO,PARENT_ID) VALUES (SEQ_MENU.NEXTVAL,12,'退卡','card/refund.jsp','',2);
INSERT INTO T_MENU (MENU_ID,MENU_SEQ,MENU_NAME,PAGE_HREF,DESC_INFO,PARENT_ID) VALUES (SEQ_MENU.NEXTVAL,13,'处方退费','daily/pres_refund.jsp','',3);
INSERT INTO T_MENU (MENU_ID,MENU_SEQ,MENU_NAME,PAGE_HREF,DESC_INFO,PARENT_ID) VALUES (SEQ_MENU.NEXTVAL,14,'领卡查询','statistics/receive_query.jsp','',4);
INSERT INTO T_MENU (MENU_ID,MENU_SEQ,MENU_NAME,PAGE_HREF,DESC_INFO,PARENT_ID) VALUES (SEQ_MENU.NEXTVAL,15,'工作量统计','statistics/work.jsp','',4);
INSERT INTO T_MENU (MENU_ID,MENU_SEQ,MENU_NAME,PAGE_HREF,DESC_INFO,PARENT_ID) VALUES (SEQ_MENU.NEXTVAL,16,'修改密码','support/modify_pwd.jsp','',5);

INSERT INTO T_MENU (MENU_ID,MENU_SEQ,MENU_NAME,PAGE_HREF,DESC_INFO,PARENT_ID) VALUES (SEQ_MENU.NEXTVAL,17,'卡入库','card/storage.jsp','',6);
INSERT INTO T_MENU (MENU_ID,MENU_SEQ,MENU_NAME,PAGE_HREF,DESC_INFO,PARENT_ID) VALUES (SEQ_MENU.NEXTVAL,18,'卡注销','card/cancel.jsp','',6);
INSERT INTO T_MENU (MENU_ID,MENU_SEQ,MENU_NAME,PAGE_HREF,DESC_INFO,PARENT_ID) VALUES (SEQ_MENU.NEXTVAL,19,'卡查询','card/query.jsp','',6);
INSERT INTO T_MENU (MENU_ID,MENU_SEQ,MENU_NAME,PAGE_HREF,DESC_INFO,PARENT_ID) VALUES (SEQ_MENU.NEXTVAL,20,'领卡审批','card/approval.jsp','',6);
INSERT INTO T_MENU (MENU_ID,MENU_SEQ,MENU_NAME,PAGE_HREF,DESC_INFO,PARENT_ID) VALUES (SEQ_MENU.NEXTVAL,21,'人员管理','system/user.jsp','',7);
INSERT INTO T_MENU (MENU_ID,MENU_SEQ,MENU_NAME,PAGE_HREF,DESC_INFO,PARENT_ID) VALUES (SEQ_MENU.NEXTVAL,22,'权限配置','system/perm.jsp','',7);
INSERT INTO T_MENU (MENU_ID,MENU_SEQ,MENU_NAME,PAGE_HREF,DESC_INFO,PARENT_ID) VALUES (SEQ_MENU.NEXTVAL,23,'菜单配置','system/menu.jsp','',7);
INSERT INTO T_MENU (MENU_ID,MENU_SEQ,MENU_NAME,PAGE_HREF,DESC_INFO,PARENT_ID) VALUES (SEQ_MENU.NEXTVAL,24,'医生排班','system/doctor.jsp','',7);
INSERT INTO T_MENU (MENU_ID,MENU_SEQ,MENU_NAME,PAGE_HREF,DESC_INFO,PARENT_ID) VALUES (SEQ_MENU.NEXTVAL,25,'日志查看','system/log.jsp','',7);
INSERT INTO T_MENU (MENU_ID,MENU_SEQ,MENU_NAME,PAGE_HREF,DESC_INFO,PARENT_ID) VALUES (SEQ_MENU.NEXTVAL,26,'参数管理','system/param.jsp','',7);
--后台用户表
INSERT INTO T_USER (USER_ID,USERNAME,PASSWORD,NAME,ROLE_ID,PARAM_SECTION_ID,PARAM_STATE_ID,DESC_INFO) VALUES
(SEQ_USER.NEXTVAL,'user1','123456','张三',3,22,1,'');
INSERT INTO T_USER (USER_ID,USERNAME,PASSWORD,NAME,ROLE_ID,PARAM_SECTION_ID,PARAM_STATE_ID,DESC_INFO) VALUES
(SEQ_USER.NEXTVAL,'user2','123456','李四',3,23,1,'');
INSERT INTO T_USER (USER_ID,USERNAME,PASSWORD,NAME,ROLE_ID,PARAM_SECTION_ID,PARAM_STATE_ID,DESC_INFO) VALUES
(SEQ_USER.NEXTVAL,'user3','123456','赵蕾',2,22,1,'');
INSERT INTO T_USER (USER_ID,USERNAME,PASSWORD,NAME,ROLE_ID,PARAM_SECTION_ID,PARAM_STATE_ID,DESC_INFO) VALUES
(SEQ_USER.NEXTVAL,'user4','123456','赵雷',2,23,1,'');
INSERT INTO T_USER (USER_ID,USERNAME,PASSWORD,NAME,ROLE_ID,PARAM_SECTION_ID,PARAM_STATE_ID,DESC_INFO) VALUES
(SEQ_USER.NEXTVAL,'user5','123456','赵磊',2,24,1,'');
INSERT INTO T_USER (USER_ID,USERNAME,PASSWORD,NAME,ROLE_ID,PARAM_SECTION_ID,PARAM_STATE_ID,DESC_INFO) VALUES
(SEQ_USER.NEXTVAL,'user6','123456','扁鹊',1,22,1,'');
INSERT INTO T_USER (USER_ID,USERNAME,PASSWORD,NAME,ROLE_ID,PARAM_SECTION_ID,PARAM_STATE_ID,DESC_INFO) VALUES
(SEQ_USER.NEXTVAL,'user7','123456','华佗',1,23,1,'');
INSERT INTO T_USER (USER_ID,USERNAME,PASSWORD,NAME,ROLE_ID,PARAM_SECTION_ID,PARAM_STATE_ID,DESC_INFO) VALUES
(SEQ_USER.NEXTVAL,'user8','123456','李时珍',1,24,1,'');


--权限表
INSERT INTO T_PERM (PERM_ID,ROLE_ID,MENU_ID,DESC_INFO) VALUES (SEQ_PERM.NEXTVAL,1,8,'');

INSERT INTO T_PERM (PERM_ID,ROLE_ID,MENU_ID,DESC_INFO) VALUES (SEQ_PERM.NEXTVAL,2,9,'');
INSERT INTO T_PERM (PERM_ID,ROLE_ID,MENU_ID,DESC_INFO) VALUES (SEQ_PERM.NEXTVAL,2,10,'');
INSERT INTO T_PERM (PERM_ID,ROLE_ID,MENU_ID,DESC_INFO) VALUES (SEQ_PERM.NEXTVAL,2,11,'');
INSERT INTO T_PERM (PERM_ID,ROLE_ID,MENU_ID,DESC_INFO) VALUES (SEQ_PERM.NEXTVAL,2,12,'');
INSERT INTO T_PERM (PERM_ID,ROLE_ID,MENU_ID,DESC_INFO) VALUES (SEQ_PERM.NEXTVAL,2,13,'');
INSERT INTO T_PERM (PERM_ID,ROLE_ID,MENU_ID,DESC_INFO) VALUES (SEQ_PERM.NEXTVAL,2,14,'');
INSERT INTO T_PERM (PERM_ID,ROLE_ID,MENU_ID,DESC_INFO) VALUES (SEQ_PERM.NEXTVAL,2,15,'');
INSERT INTO T_PERM (PERM_ID,ROLE_ID,MENU_ID,DESC_INFO) VALUES (SEQ_PERM.NEXTVAL,2,16,'');

INSERT INTO T_PERM (PERM_ID,ROLE_ID,MENU_ID,DESC_INFO) VALUES (SEQ_PERM.NEXTVAL,3,17,'');
INSERT INTO T_PERM (PERM_ID,ROLE_ID,MENU_ID,DESC_INFO) VALUES (SEQ_PERM.NEXTVAL,3,18,'');
INSERT INTO T_PERM (PERM_ID,ROLE_ID,MENU_ID,DESC_INFO) VALUES (SEQ_PERM.NEXTVAL,3,19,'');
INSERT INTO T_PERM (PERM_ID,ROLE_ID,MENU_ID,DESC_INFO) VALUES (SEQ_PERM.NEXTVAL,3,20,'');
INSERT INTO T_PERM (PERM_ID,ROLE_ID,MENU_ID,DESC_INFO) VALUES (SEQ_PERM.NEXTVAL,3,21,'');
INSERT INTO T_PERM (PERM_ID,ROLE_ID,MENU_ID,DESC_INFO) VALUES (SEQ_PERM.NEXTVAL,3,22,'');
INSERT INTO T_PERM (PERM_ID,ROLE_ID,MENU_ID,DESC_INFO) VALUES (SEQ_PERM.NEXTVAL,3,23,'');
INSERT INTO T_PERM (PERM_ID,ROLE_ID,MENU_ID,DESC_INFO) VALUES (SEQ_PERM.NEXTVAL,3,24,'');
INSERT INTO T_PERM (PERM_ID,ROLE_ID,MENU_ID,DESC_INFO) VALUES (SEQ_PERM.NEXTVAL,3,25,'');
INSERT INTO T_PERM (PERM_ID,ROLE_ID,MENU_ID,DESC_INFO) VALUES (SEQ_PERM.NEXTVAL,3,26,'');

--一卡通表
INSERT INTO T_CARD (CARD_ID,CARD_CODE,CREATE_TIME,SALE_TIME,APPLY_ID,SALE_USER_ID,PATIENT_ID,PARAM_STATE_ID,AMOUNT,DEPOSIT,DESC_INFO) VALUES
(SEQ_CARD.NEXTVAL,'FZ00000001',SYSDATE,NULL,NULL,NULL,NULL,4,0,0,'');
INSERT INTO T_CARD (CARD_ID,CARD_CODE,CREATE_TIME,SALE_TIME,APPLY_ID,SALE_USER_ID,PATIENT_ID,PARAM_STATE_ID,AMOUNT,DEPOSIT,DESC_INFO) VALUES
(SEQ_CARD.NEXTVAL,'FZ00000002',SYSDATE,NULL,NULL,NULL,NULL,4,0,0,'');
INSERT INTO T_CARD (CARD_ID,CARD_CODE,CREATE_TIME,SALE_TIME,APPLY_ID,SALE_USER_ID,PATIENT_ID,PARAM_STATE_ID,AMOUNT,DEPOSIT,DESC_INFO) VALUES
(SEQ_CARD.NEXTVAL,'FZ00000003',SYSDATE,NULL,NULL,NULL,NULL,4,0,0,'');
INSERT INTO T_CARD (CARD_ID,CARD_CODE,CREATE_TIME,SALE_TIME,APPLY_ID,SALE_USER_ID,PATIENT_ID,PARAM_STATE_ID,AMOUNT,DEPOSIT,DESC_INFO) VALUES
(SEQ_CARD.NEXTVAL,'FZ00000004',SYSDATE,NULL,NULL,NULL,NULL,4,0,0,'');
INSERT INTO T_CARD (CARD_ID,CARD_CODE,CREATE_TIME,SALE_TIME,APPLY_ID,SALE_USER_ID,PATIENT_ID,PARAM_STATE_ID,AMOUNT,DEPOSIT,DESC_INFO) VALUES
(SEQ_CARD.NEXTVAL,'FZ00000005',SYSDATE,NULL,NULL,NULL,NULL,4,0,0,'');
INSERT INTO T_CARD (CARD_ID,CARD_CODE,CREATE_TIME,SALE_TIME,APPLY_ID,SALE_USER_ID,PATIENT_ID,PARAM_STATE_ID,AMOUNT,DEPOSIT,DESC_INFO) VALUES
(SEQ_CARD.NEXTVAL,'FZ00000006',SYSDATE,NULL,NULL,NULL,NULL,4,0,0,'');

COMMIT;











