DELETE FROM T_APPLY;
DROP SEQUENCE SEQ_APPLY;
CREATE SEQUENCE SEQ_APPLY;

DELETE FROM T_APPOINT;
DROP SEQUENCE SEQ_APPOINT;
CREATE SEQUENCE SEQ_APPOINT;

DELETE FROM T_CARD;
DROP SEQUENCE SEQ_CARD;
CREATE SEQUENCE SEQ_CARD;

DELETE FROM T_LOG;
DROP SEQUENCE SEQ_LOG;
CREATE SEQUENCE SEQ_LOG;

DELETE FROM T_MENU;
DROP SEQUENCE SEQ_MENU;
CREATE SEQUENCE SEQ_MENU;

DELETE FROM T_PARAM;
DROP SEQUENCE SEQ_PARAM;
CREATE SEQUENCE SEQ_PARAM;

DELETE FROM T_PATIENT;
DROP SEQUENCE SEQ_PATIENT;
CREATE SEQUENCE SEQ_PATIENT;

DELETE FROM T_PERM;
DROP SEQUENCE SEQ_PERM;
CREATE SEQUENCE SEQ_PERM;

DELETE FROM T_PRES;
DROP SEQUENCE SEQ_PRES;
CREATE SEQUENCE SEQ_PRES;

DELETE FROM T_RECORD;
DROP SEQUENCE SEQ_RECORD;
CREATE SEQUENCE SEQ_RECORD;

DELETE FROM T_ROLE;
DROP SEQUENCE SEQ_ROLE;
CREATE SEQUENCE SEQ_ROLE;

DELETE FROM T_USER;
DROP SEQUENCE SEQ_USER;
CREATE SEQUENCE SEQ_USER;
